name: workflow

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  "0 10 1 * *"

jobs:
  tests:
    runs-on: ubuntu-cloud-runner
    steps:
      - uses: actions/checkout@v4
      - run: |
          env
